### ISSUE TITLE
AWS AMI : Allow ability to not update FW version.

### ISSUE THREAD

**Issue by ygoodmn** [CheckPointSW/CloudGuardIaaS#142]
Hi,
After lots of troubleshooting FW Gateway version deployed last week, today running the terraform the version of the AWS AMI in the launch configuration showed a downgraded version, but didn't know to update the instances until you refresh or autoscale.

Expected:
Able to indicate which AWS AMI  to use. Not not overwrite current  AWS AMI version of Gateway FW.
Allowing either the following:
AMI : as variable
AMI : as dynamic from https://cgi-cfts.s3.amazonaws.com/utils/amis.yaml

Current:
The autoscale goes to module for ami's and get's the AMI, and will update the launchconfiguration template, but no version will change unless an auto-scale or refresh is done.
terraform/aws/autoscale/main.tf
36: ` image_id = module.amis.ami_id`

Details:
Last week when deploying FW gateway autoscaling it installed version: R80.40-294.943, this week when running terraform it  deployed R80.40-294.936 to only the launch configuration. 

As it seems there is some issue in this version R80.40-294.943, didn't know to refresh to the older version. (As shown in https://cgi-cfts.s3.amazonaws.com/utils/amis.yaml is now pointing to  R80.40-294.936 )

Not Working: R80.40-294.943 the AWS LB was showing unhealthy instances . Though the NAT looked ok in the SmartConsole, In logs showed the following error 
`IP routing failed (bridge routing failure)`

Is there a site where can see which version is a working version or if there are issues with the version and should downgrade.

-Thanks

chkp-yaakovg

**Comment by chkp-romanka** [comment]
Hi @ygoodmn 
You can see the images versions in the sk125252
https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk125252

You should use R80.40-294.936 image. The R80.40-294.943 image version is aimed for GWLB solution and shouldn't replace the  R80.40-294.936 version in amis.yaml. We understand the root cause of the problem and will fix it

We will add ability to chose specific AMI in our templates
Thanks,
Roman

**Comment by sankargopal-77** [comment]
Hi , 
Apologies for adding extra issues, but let me know I can create separate issue.

we are facing similar problem but slightly different. We are using checkpoint management version R81.10-335.942, We were using AMI created in July 2021 and recently got upgraded in November. 

We would like to have same ability to pass AMI id instead of management license version.

**Comment by chkp-romanka** [comment]
The proposal added to the 2023 roadmap
