### ISSUE TITLE
error with the message to launch the template 

### ISSUE THREAD

**Issue by raylauhk** [CheckPointSW/CloudGuardIaaS#369]
╷
│ Error: creating Auto Scaling Group (Check-Point-ASG-tf2024050909155111710000000d): ValidationError: You must use a valid fully-formed launch template. In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=263gtcd87e2xefwbacsdwvorx
│       status code: 400, request id: 1943e783-0eda-4b2d-8ce6-a80318e01153
│ 
│   with module.tgw-gwlb.module.gwlb.module.autoscale_gwlb.aws_autoscaling_group.asg,
│   on ../autoscale-gwlb/main.tf line 77, in resource "aws_autoscaling_group" "asg":
│   77: resource "aws_autoscaling_group" "asg" {
│ 
╵
╷
│ Error: creating EC2 Instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=5y97v3ikpvbmnkbdfpuw4fdra
│       status code: 401, request id: 377a1a9a-d5c0-45a6-8c5e-8393a55233bc
│ 
│   with module.tgw-gwlb.module.gwlb.module.management[0].aws_instance.management-instance,
│   on ../management/main.tf line 120, in resource "aws_instance" "management-instance":
│  120: resource "aws_instance" "management-instance" {

**Comment by chkp-romanka** [comment]
Hello @raylauhk 
In order to deploy CloudGuard for AWS Auto Scale Group solution  you need to subscribe to relevant listing in AWS marketplace and accept terms.
You can find instructions on how to do it in the Auto Scale Group admin guide -> Deployment Steps -> Subscribing to Check Point CloudGuard Network
https://sc1.checkpoint.com/documents/IaaS/WebAdminGuides/EN/CloudGuard_Network_for_AWS_AutoScaling_DeploymentGuide/Default.htm
