### ISSUE TITLE
Use resource azurerm_virtual_hub_routing_intent instead of python script

### ISSUE THREAD

**Issue by milkmanrox** [CheckPointSW/CloudGuardIaaS#382]
To create/destroy a routing intent in an Azure vWAN Hub, this repository seems to leverage a python script.

Can this be moved to the native terraform resource of "azurerm_virtual_hub_routing_intent" instead? It doesn't make sense to break out to a python script unnecessarily and adds an additional dependency on the operators machine.

**Comment by chkp-yairra** [comment]
Hi @milkmanrox,

Thank you for your feedback.

When using the dedicated resource for routing-intent deployment (azurerm_virtual_hub_routing_intent), deploying another Network Virtual Appliance (NVA) into the same Hub can lead to unexpected behavior. 
Specifically, adding a new NVA requires creating a new azurerm_virtual_hub_routing_intent resource with a different name from the existing one. 
Unfortunately, the new routing intent policy does not override the existing policy of the Hub. This is likely not the expected result when deploying a new NVA with a routing intent option.

On the other hand, using the Python script allows us to successfully override the existing routing intent policy of the Hub, ensuring the new configuration takes effect as expected.

We've already asked Microsoft to provide a solution for this issue and we will update the templates to use the dedicated resource instead of the Python script once we get the solution.

Best regards,

Yair
